name: dart_async_coingecko_task
description: A Dart assignment for learning async programming with CoinGecko API
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0

dev_dependencies:
  lints: ^3.0.0
